"""
Description: MARC Data Access Layer (DAL) abstracting MARCXML records. 
             Provides a safe interface through the Null Object Pattern.
Usage: 
    This is intended to be imported as a module in your other validation scripts.

Generated by: Antigravity

Version: 0.1.0 2026-03-21marc_xml_impl.py

License: CC BY-NC-SA 4.0, https://creativecommons.org/licenses/by-nc-sa/4.0/

Author: Graeme Williams
Email: carryonwilliams@gmail.com
"""

import xml.etree.ElementTree as ET
from marc_interfaces import BaseRecord, BaseField, BaseSubfield, NullField, NullSubfield

class XMLSubfield(BaseSubfield):
    def __init__(self, element):
        self.element = element

    @property
    def code(self):
        return self.element.attrib.get('code', '')

    @property
    def value(self):
        return self.element.text if self.element.text is not None else ""

    def __bool__(self):
        return True


class XMLField(BaseField):
    def __init__(self, element):
        self.element = element
        self.ns = {'marc': 'http://www.loc.gov/MARC21/slim'}
        # Safely derive the tag name ignoring the namespace for boolean checks
        self._tag = self.element.tag.split('}')[-1] if '}' in self.element.tag else self.element.tag

    @property
    def is_control_field(self):
        return self._tag == 'controlfield' or self._tag == 'leader'

    @property
    def is_data_field(self):
        return self._tag == 'datafield'

    @property
    def tag(self):
        return self.element.attrib.get('tag', self._tag)

    @property
    def indicator1(self):
        if self.is_control_field:
            return " "
        return self.element.attrib.get('ind1', ' ')

    @property
    def indicator2(self):
        if self.is_control_field:
            return " "
        return self.element.attrib.get('ind2', ' ')

    @property
    def data(self):
        """
        Returns text content safely as a string for control fields/leader.
        This provides safe slicing mechanics natively utilizing standard Python strings
        (e.g field.data[33:34] evaluates to '' if out of bounds instead of IndexError)
        """
        text = self.element.text
        return text if text is not None else ""

    def get_subfield(self, code) -> BaseSubfield:
        if self.is_control_field:
            return NullSubfield()
        
        subfield_elem = self.element.find(f'marc:subfield[@code="{code}"]', self.ns)
        if subfield_elem is not None:
            return XMLSubfield(subfield_elem)
        return NullSubfield()

    def get_subfields(self, code=None) -> list[BaseSubfield]:
        if self.is_control_field:
            return []
            
        if code is None:
            subfield_elems = self.element.findall('marc:subfield', self.ns)
        else:
            subfield_elems = self.element.findall(f'marc:subfield[@code="{code}"]', self.ns)
        return [XMLSubfield(elem) for elem in subfield_elems]

    @property
    def value(self) -> str:
        return self.data

    def __bool__(self):
        return True


class XMLRecord(BaseRecord):
    def __init__(self, element):
        self.element = element
        self.ns = {'marc': 'http://www.loc.gov/MARC21/slim'}

    def get_field(self, tag: str) -> BaseField:
        if tag.lower() == 'leader' or tag == 'ldr':
            field_elem = self.element.find('marc:leader', self.ns)
            if field_elem is not None:
                return XMLField(field_elem)
            return NullField()
            
        if tag.isdigit() and int(tag) < 10:
            field_elem = self.element.find(f'marc:controlfield[@tag="{tag}"]', self.ns)
            if field_elem is not None:
                return XMLField(field_elem)
            return NullField()
            
        field_elem = self.element.find(f'marc:datafield[@tag="{tag}"]', self.ns)
        if field_elem is not None:
            return XMLField(field_elem)
        return NullField()

    def get_fields(self, tag: str) -> list[BaseField]:
        if tag.lower() == 'leader' or tag == 'ldr':
            field_elem = self.element.find('marc:leader', self.ns)
            if field_elem is not None:
                return [XMLField(field_elem)]
            return []
            
        if tag.isdigit() and int(tag) < 10:
            field_elems = self.element.findall(f'marc:controlfield[@tag="{tag}"]', self.ns)
            return [XMLField(elem) for elem in field_elems]
            
        field_elems = self.element.findall(f'marc:datafield[@tag="{tag}"]', self.ns)
        return [XMLField(elem) for elem in field_elems]

    def get_datafields(self) -> list[BaseField]:
        field_elems = self.element.findall('marc:datafield', self.ns)
        return [XMLField(elem) for elem in field_elems]

    def get_controlfields(self) -> list[BaseField]:
        field_elems = self.element.findall('marc:controlfield', self.ns)
        return [XMLField(elem) for elem in field_elems]
